# This is a basic workflow to help you get started with Actions(((00)))...... ...... ......

name: CI

# Controls when the action will run.(((00))) 
on:
  # Triggers the workflow on push or pull request events but only for the main branch(((00)))
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab(((00)))
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel(((00)))
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on(((00)))
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job(((00)))
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it(((00)))
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell(((00)))
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell(((00)))
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
# Runs a set of commands using the runners shell(((00)))
# Runs a set of commands using the runners shell(((00)))
# Runs a set of commands using the runners shell(((00)))

# Lost the Muzero math; redo it better ((remember your objective function).
# Use this as a notepad in order to transfer the Muzero math. 























# ...... ...... ......
# xtrmnt..
# xtrmnt.
# strangely enough the math reapeared magically which highlights the importance on keeping
# all data offline......status report check; understanding of the markets beyond guage theory; ruff understanding of C/C++ implementation on a higher abstraction level & Python and computer hardware......
# Things to improve on over the next 8 quaters: i)Programming. ii)calculus, trigonometry and algebra. iii) time scale sensitive project management

